AWSTemplateFormatVersion: 2010-09-09
Description: Creates/upadtes a linux server. Installs apache, and wget. Pulls basic html page from github. Verify: security group ID, subnet ID, AMI, keypair. 
Resources:
  myENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: A nice description.
      SourceDestCheck: 'false'
      GroupSet:
        - sg-055c055ea1f7b8c99
      SubnetId: subnet-b60753fa   
      
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-2c
      ImageId: "ami-0f57b4cec24530068"
      KeyName: "keypairMAY"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install httpd -y
          service httpd start                
          chkconfig httpd on
          sudo yum install -y wget
          cd /var/www/html
          wget https://raw.githubusercontent.com/Andrews-repo/DEV/master/Basic%20Web%20Host/index.html
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "8"
      InstanceType: 't2.micro'
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref myENI
          DeviceIndex: 0     
