AWSTemplateFormatVersion: 2010-09-09
Resources:
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Properties:
      LaunchTemplateName: test
      LaunchTemplateData:
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: 8
            DeviceName: /dev/sdf
        ImageId: ami-0022aaab3c3ee7abd
        InstanceType: t2.micro
        KeyName: workkey
        Monitoring:
          Enabled: true
        SecurityGroupIds:
          - sg-0da8c45dd859d8183
  myASG:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      AutoScalingGroupName: myASG
      MinSize: '1'
      MaxSize: '6'
      DesiredCapacity: '1'
      HealthCheckGracePeriod: 300
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      AvailabilityZones:
        'Fn::GetAZs': us-east-1
