AWSTemplateFormatVersion: 2010-09-09
Parameters:
    Password:
        NoEcho: 'true'
        Type: String
        Description: New account password
Resources:
  MyUser:
    Type: AWS::IAM::User
    Properties:
      UserName: #STRING
      LoginProfile:
        Password: 
          !Ref 'Password'
  MyGroup:
    Type: AWS::IAM::Group  
    Properties:
        GroupName: #STRING
        ManagedPolicyArns:
         - #ARN
         - #ARN  
  Users:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !Ref 'MyGroup'
      Users: [!Ref 'MyUser']
